                                                  ############################################################

                                                  #                  VIDEO LABELLING STEP

                                                  ############################################################

# PATHS
input_folder_lab: 
    '/repo/porri/nyst_video_cartelle'
flattened_folder_lab: 
    '/repo/porri/nyst_flatten_video'  
output_folder_lab:
    '/repo/porri/nyst_labelled_videos'

# VALUES CONFIGURATION
clip_duration:
    5
overlapping:
    3

                                                  ############################################################

                                                  #             VIDEO FEATURES EXTRACTION STEP

                                                  ############################################################
# PATHS
input_folder_extr:
    '/repo/porri/nyst_labelled_videos/videos'
output_folder_extr:
    '/repo/porri/nyst_labelled_videos'
  

                                                  ############################################################

                                                  #             PREPROCESS AND AUGMENTATION STEP

                                                  ############################################################  
# PATHS
csv_input_file:
    '/repo/porri/nyst_labelled_videos/train_dataset.csv'
csv_label_file:
    '/repo/porri/nyst_labelled_videos/labels.csv'
new_csv_file:
    '/repo/porri/nyst_labelled_videos/video_features_interp.csv'
# VALUES CONFIGURATION
preprocess:
    ['cubic_interpolation']
augmentation:
    [] #'augment_data'    

                                                  ############################################################

                                                  #                   TRAINING FULL NET STEP

                                                  ############################################################  

save_path:
    '/repo/porri/nyst_labelled_videos/best_model.pth'
save_path_info:
    '/repo/porri/nyst_labelled_videos'
save_path_wb:
    '/repo/porri/nyst/models_1'
