# SWEEP SETTINGS
project: nyst_detection

method: random  # Can be 'random' or 'grid'

parameters:
  batch_size:
    values: [8, 16, 32, 64, 128]
  lr:
    values: [0.01, 0.003, 0.001, 0.0003, 0.0001, 0.00003, 0.00001]
  epochs:
    values: [1000]
  threshold_correct:
    values: [0.5]
  patience:
    values: [5, 10, 20, 40, 60]
  optimizer:
    values: ['adam'] #'sgd'    
  criterion:
    values: ['BCELoss','MSELoss'] 

metric:
  goal: minimize
  name: kfold_avg_accuracy

early_terminate:
  type: hyperband
  min_iter: 10  
  s: 2  

#run_cap: 2
concurrency: 1 #number of concurrent processes
